[development]
address = "0.0.0.0"
port = 8000
# worker mean thread load balancer
workers = 4
keep_alive = 5
log = "normal"
secret_key = "pkOHDdmnav3Ev0AmizhgxfnTD824OKoFarbe8XmZmzM="
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "normal"
secret_key = "pkOHDdmnav3Ev0AmizhgxfnTD824OKoFarbe8XmZmzM="
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5
log = "critical"
secret_key = "pkOHDdmnav3Ev0AmizhgxfnTD824OKoFarbe8XmZmzM="
limits = { forms = 32768 }